# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('name', models.TextField(blank=True)),
                ('idea', models.TextField(blank=True)),
                ('goal', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('preferred_skills', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
