# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('projectwe', '0002_auto_20160921_0830'), ('projectwe', '0003_user_country'), ('projectwe', '0004_auto_20161212_1452')]

    dependencies = [
        ('projectwe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='CH', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_projects', to='projectwe.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_projects', to='projectwe.User'),
        ),
    ]
